language: php
php:
  - '5.6'
  - '7.0'

addons:
   ssh_known_hosts: mytent.site

before_install:
- openssl aes-256-cbc -K $encrypted_b6b3065e2137_key -iv $encrypted_b6b3065e2137_iv
  -in deploy-key.enc -out deploy-key -d

install:
- composer install --no-interaction;